import esbuild from 'esbuild';
import process from 'node:process';

const banner = `/*
Markday — bundled by esbuild from src/. Do not edit this file directly;
edit src/*.js and run \`npm run build\`.
*/`;

const prod = process.argv[2] === 'production';

const ctx = await esbuild.context({
    banner: { js: banner },
    entryPoints: ['src/main.js'],
    bundle: true,
    external: ['obsidian', 'electron', '@codemirror/*', '@lezer/*', 'node:*'],
    format: 'cjs',
    target: 'es2020',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
});

if (prod) {
    await ctx.rebuild();
    process.exit(0);
} else {
    await ctx.watch();
}
